# Generated by Django 5.0.6 on 2024-06-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrichment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comercio",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="keyword",
            old_name="merchant_id",
            new_name="merchant",
        ),
        migrations.RenameField(
            model_name="transaccion",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="transaccion",
            old_name="merchant_id",
            new_name="merchant",
        ),
    ]
